In [28]:
import numpy as np

rng = np.random.RandomState(3)
upp = np.triu(rng.uniform(size=[3, 3]), k=1)
symm = upp + upp.T

upp2 = np.triu(rng.uniform(size=[3, 3]), k=1)
skew = upp2 - upp2.T

In [39]:
np.linalg.eig(symm)[0]

array([ 1.29413608, -0.28189814, -1.01223795])

In [40]:
np.linalg.eig(skew)[0]

array([ 5.15392317e-17+0.j       , -5.55111512e-17+0.8166455j,
       -5.55111512e-17-0.8166455j])

In [41]:
np.linalg.eig(symm + skew)[0]

array([-0.90131713,  0.11413084,  0.78718629])

In [42]:
np.linalg.eig(skew + np.eye(3))[0]

array([1.+0.j       , 1.+0.8166455j, 1.-0.8166455j])